<?php $tgl1=$result->c_d($_GET['tgl1']);$tgl2=$result->c_d($_GET['tgl2']);$branch=$result->c_d($_GET['branch']);$kdkop=$result->c_d($_GET['kdkop']);$kdsales = $result->c_d($_GET['kdsales']);$pilih=$result->c_d($_GET['p']);$xt=date_angka(date_sql($tgl2));$tabel=$tabel_kredit.$xt;
if($branch=='0111'){
	if ($kdsales=='9'){
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.tgtran>='$tgl1' AND a.tgtran<='$tgl2' GROUP BY a.produk,a.kdsales,a.jangka ORDER BY a.produk,a.kdsales,a.jangka");
	}else{
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.tgtran>='$tgl1' AND a.tgtran<='$tgl2' AND a.kdsales='$kdsales' GROUP BY a.produk,a.kdsales,a.jangka ORDER BY a.produk,a.kdsales,a.jangka");
	}	
}else{
	if ($kdsales=='9'){
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.tgtran>='$tgl1' AND a.tgtran<='$tgl2' AND a.branch='$branch' GROUP BY a.produk,a.kdsales,a.jangka ORDER BY a.produk,a.kdsales,a.jangka");
	}else{
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.tgtran>='$tgl1' AND a.tgtran<='$tgl2' AND a.branch='$branch' AND a.kdsales='$kdsales' GROUP BY a.produk,a.kdsales,a.jangka ORDER BY a.produk,a.kdsales,a.jangka");
	}
}
?>