<?php $bln=$result->c_d($_GET['bln']);$thn=$result->c_d($_GET['thn']);$branch=$result->c_d($_GET['branch']);$produk=$result->c_d($_GET['kdsales']);$pilih=$result->c_d($_GET['p']);$tabel=$tabel_kredit.$bln.substr($thn,2,2);
if($branch=='0111'){
	if ($produk=='9'){
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.kkbayar,a.nmbayar,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 GROUP BY a.kkbayar,a.kdsales,a.jangka,a.suku ORDER BY a.kkbayar,a.kdsales,a.jangka,a.suku");
	}else{
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.kkbayar,a.nmbayar,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.produk='$produk' GROUP BY a.kkbayar,a.kdsales,a.jangka,a.suku ORDER BY a.kkbayar,a.kdsales,a.jangka,a.suku");
	}	
}else{
	if ($produk=='9'){
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.kkbayar,a.nmbayar,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.branch='$branch' GROUP BY a.kkbayar,a.kdsales,a.jangka,a.suku ORDER BY a.kkbayar,a.kdsales,a.jangka,a.suku");
	}else{
		$hasil=$result->query_lap("SELECT a.branch,a.nonas,a.sufix,a.norek,a.noreks,a.jangka,a.produk,a.kkbayar,a.nmbayar,a.suku,SUM(a.nomi) AS nomi,a.kdkop,SUM(a.meterai) AS meterai,SUM(a.premi) AS premi,SUM(a.jumpremi) AS jumpremi,SUM(a.jumrefund) AS jumrefund,SUM(a.jumprovisi) AS jumprovisi,SUM(a.jumadm) AS jumadm,SUM(a.jumbtl+a.simpokok+a.simwajib) AS jumbtl,SUM(a.plunas) AS plunas,SUM(a.blunas) AS blunas,SUM(a.alunas) AS alunas,SUM(a.dbunga) AS dbunga,SUM(a.simpokok) AS simpokok,SUM(a.simwajib) AS simwajib,a.kdsales,SUM(a.pot_angsuran) AS pot_angsuran,SUM(a.jum_period) AS jum_period,count(*) AS orang,b.nmproduk,c.nama FROM $tabel a JOIN debit1 b ON a.produk=b.kdproduk JOIN sales c ON a.kdsales=c.idsales WHERE a.kdaktif=1 AND a.branch='$branch' AND a.produk='$produk' GROUP BY a.kkbayar,a.kdsales,a.jangka,a.suku ORDER BY a.kkbayar,a.kdsales,a.jangka,a.suku");
	}	
}
?>