<?php
$tabel_ptkp='gaji.tabel_ptkp';
$tabel_master='gaji.master';
$tabel_organisasi='gaji.tabel_organisasi';
$tabel_wilayah='gaji.tabel_wilayah';
$tabel_lokasi='gaji.tabel_lokasi';
$tabel_jabatan='gaji.tabel_jabatan';
$tabel_grade='gaji.tabel_grade';
$tabel_absensi='gaji.tabel_absensi';
$tabel_riwayat='gaji.riwayat_pekerjaan';
$tabel_riwayat_ja='gaji.riwayat_jabatan';
$tabel_branch='nabasa.tblkantor';
$tabel_kabupaten='nabasa.kode_kabupaten';
$tabel_propinsi='nabasa.kode_propinsi';
$tabel_Transaksi='nabasa.'.$tabelTransaksi;
?>