<?php
$huruf = array("PILIHAN","MENINGGAL DUNIA","JAMINAN TIDAK ADA/PALSU","DOUBLE PINJAMAN PADA BANK","PENGURUSAN KLAIM ASURANSI","GAJI TIDAK TERBIT/STOP","DEBITUR NAKAL/TIDAK BAIK","MUTASI GAJI UANG PENSIUN","GAJI MINUS/TURUN","TIDAK TERTAGIH PADA KANTOR BAYAR");$i = 0;
while($i<10){
	if($ketkolek == $i){
		$xkkolek=$huruf[$i];
	}
	$i++;
}
?>